### ISSUE TITLE
Support multiple indexes

### ISSUE THREAD

**Issue by hadley** [RolfBremer/in-dexter#10]
It'd be cool if in-dexter could generate multiple indexes, a la imakeidx.

**Comment by RolfBremer** [comment]
I will look into it!

**Comment by RolfBremer** [comment]
OK, we have implemented a first version supporting multiple indexes. 
I will test it some more and document it, before merging. May I ask you for a specific use case where you need separate indexes?

**Comment by hadley** [comment]
I used it for a book I self-published on cocktails (https://github.com/hadley/cocktails/tree/master/book) — the book is organised by primary spirit, so it's useful to have one index for the name of the cocktail and one index for the other ingredients. My plan is to work on converting the book from latex to typst now that [quarto](https://quarto.org) supports it.

**Comment by RolfBremer** [comment]
Support for multiple indexes is now in the main branch.
Release as a typst package will follow soon.
