### ISSUE TITLE
[Feature Request] Case insensitive option for index?

### ISSUE THREAD

**Issue by iandol** [RolfBremer/in-dexter#11]
Currently `#label[item]` and `#label[Item]` will generate two alphabetical entries in the index. It would be nice if there was an **option** in `#make-index` to choose to be case insensitive, so if enabled then both entries would be combined under `I` and `Item`.

**Comment by RolfBremer** [comment]
Yes, I had some Issues with that, too. I will look into it soon.

**Comment by Atreyu-94** [comment]
Same problem here. I think case insensitive should be default maybe. Btw, this package is very useful and very easy and intuitive to use.

**Comment by RolfBremer** [comment]
Support for advanced case handling is now in the main branch.
Release as a typst package will follow soon.

**Comment by produnis** [comment]
Hi and thx for this extension, however, how do I re-activate case-sensitivity?

**Comment by produnis** [comment]
Ah,
I added to my typst 
```
// First letter "as is" for in-dexter
#let first-letter-asis(entry) = {
  entry
}
```

and then updated my call to

```
#columns(3)[#make-index(use-page-counter: true,
                        entry-casing: k => first-letter-asis(k),)]
```

Now it is case-sensitive again, just as I want it.

thx for this package, it is really helpful!
