### ISSUE TITLE
[Feature Request] LaTeX style hierarchy

### ISSUE THREAD

**Issue by iandol** [RolfBremer/in-dexter#12]
In LaTeX you can use `index{Group!Item}` to make a hierarchy. In in-dexter that is done by `#index("Group", "Item")` but for interoperability it would be nice if you could also add support for a `#index[Group!Item]` so the index key would be the same between Typst and LaTeX (thinking about ease of converson between formats). You would just split the `Group!Item` at the ! and then get the group and item...

**Comment by RolfBremer** [comment]
Support for the LaTeX index grouping syntax is now in the main branch.
Release as a typst package will follow soon.
