### ISSUE TITLE
Conflict using `glossarium` and `in-dexter`

### ISSUE THREAD

**Issue by Atreyu-94** [RolfBremer/in-dexter#13]
My problem is when I have an acronym that I plan to use with `glossarium` and this acronym should also be in the index. Is there a solution for it to appear on both sides without conflict?

**Comment by RolfBremer** [comment]
I have not used glossarium yet, but will have a look into it.

**Comment by RolfBremer** [comment]
Ok, I am not sure I understood your question right. I habe tried both packages together now, and it works just fine. I also created a simple function like this:

```typ
#let in-gls(key) = {
  gls(key)
  index(key)
}
```

to add an entry to both, the glossarium as well as the index at once. Ist this, what you wanted to achieve?

**Comment by Atreyu-94** [comment]
Ok, this stuff is working :3 Thx a lot!!
