### ISSUE TITLE
Publishing v0.4.x

### ISSUE THREAD

**Issue by joholl** [RolfBremer/in-dexter#16]
@RolfBremer 

First up: this package is great! Thank you for making and maintaining this.

Could you please upload version v0.4.x to the [typst universe](https://typst.app/universe/package/in-dexter)? I am already relying on the `display` parameter and currently forced to use a local copy since the latest version on the universe is v0.3.0.

Thanks! :)

**Comment by RolfBremer** [comment]
OK, version 0.4.2 is submitted to typst universe. Waiting for approval.

**Comment by RolfBremer** [comment]
Ok, it is published!
